### ISSUE TITLE
for Elm 0.17.0

### ISSUE THREAD

**Issue by forresto** [alinz/elm-vector2d#1]
I'm new, but I think it's only a matter of changing https://github.com/alinz/elm-vector2d/blob/150ed17d7f8c4d4274f6386a0837f361531882ff/src/Vector2D.elm#L1 to 

`module Vector2D exposing (..)`

https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.17.md#updating-syntax

**Comment by alinz** [comment]
@forresto Thanks, will you give me a PR?

**Comment by jethrolarson** [comment]
Now for 0.18

**Comment by alinz** [comment]
thanks to @jethrolarson, it has been merged.
